#use all rules by default

rules:

  #error

  attribute-quotes: 2
  bem-depth: 2
  border-zero: 2
  brace-style: 2
  class-name-format:
    - 2
    - convention: hyphenatedbem
  clean-import-paths: 2
  declarations-before-nesting: 2
  empty-args: 2
  empty-line-between-blocks: 2
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline: 2
  force-attribute-nesting: 2
  force-element-nesting: 2
  force-pseudo-nesting: 2
  function-name-format: 2
  hex-length: 2
  hex-notation: 2
  id-name-format: 2
  indentation: 2
  leading-zero:
    - 2
    - include: true
  mixins-before-declarations: 2
  mixin-name-format: 2
  no-attribute-selectors: 2
  no-color-hex: 2
  no-combinators: 2
  no-css-comments: 2
  no-debug: 2
  no-empty-rulesets: 2
  no-extends: 2
  no-ids: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-qualifying-elements: 2
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 2
  no-url-domains: 2
  no-url-protocols: 2
  no-warn: 2
  one-declaration-per-line: 2
  placeholder-in-extend: 2
  placeholder-name-format: 2
  property-sort-order: 2
  pseudo-element: 2
  quotes:
    - 2
    - style: double
  shorthand-values: 2
  space-after-bang: 2
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-bang: 2
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens: 2
  trailing-semicolon: 2
  url-quotes: 2
  variable-name-format: 2
  zero-unit: 2

  #warning

  max-file-line-count: 1
  max-line-length:
    - 1
    - length: 120
  no-important: 1
  no-duplicate-properties: 1
  no-universal-selectors: 1

  #unenforced

  #nest elements and modifiers
  #pad blocks that contain padding
  #prefer inline declarations
  #sort rulesets

  #off

  nesting-depth: 0
  no-color-keywords: 0
  no-color-literals: 0
  no-disallowed-properties: 0
  no-misspelled-properties: 0
  no-vendor-prefixes: 0
  property-units: 0
  single-line-per-selector: 0
  variable-for-property: 0
